name: A workflow for my Hello World file
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ development ]
jobs:
  build:
    name: Pushing builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Automated action with docker
        uses: ./action-a
        with:
          MY_NAME: "test"
      - name: medic-conf install
        run: npm install -g medic-conf@1.20.1
      - name: run medic-conf
        run: medic-conf --version
      - name: set up pyxform
        run: python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
      - name: clone project 
        uses: actions/checkout@v1
        with:
          repository: livinggoods/config-kenya-lg-isiolo
          token: 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
          path: config-kenya-lg-isiolo
          ref: development
      - name: setting details
        run: |
          git config user.name kennethatria
          git config user.email kennethatria@gmail.com
          pwd

      #- name : build project
      # run : medic-conf compile-app-settings convert-app-forms -- assessment

            

