name: A workflow for my Hello World file

on:
  push:
    branches:
      - "release/*"
  #pull_request:
  #  branches: [ development ]
jobs:
  build:
    name: Pushing builds
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'development'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
        - uses: ./action-a
        with:
          MY_NAME: ATRIA

            

