name: Automatic Merge release - development

on:
  pull_request:
    branches:
      - 'release/**'
    types: [ closed ]

jobs:
  merge-job-development: # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == "release/GSE-target" # add check the target branch merged into is development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'development'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
      - run: |
          echo PR #${{ github.event.number }} has been merged
          echo target of PR ${{ github.event.pull_request.base.ref }}
          echo source of PR ${{ github.event.pull_request.head.ref }}
          echo this works !!!

          
  push-config-job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo push config
