name: A workflow for my Hello World file
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ development ]
jobs:
  build:
    name: Pushing builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Automated action
        uses: ./action-a
        with:
          MY_NAME: "test"
      - name: setting up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
            

