name: A workflow for my Hello World file

on:
  push:
    branches:
      - "release/*"
  pull_request:
    branches: [ development ]
jobs:
  build:
    name: Pushing builds
    runs-on: ubuntu-latest
    steps:
      - uses: ./action-b

            

