name: Automatic Merge release - feature-something

on:
  workflow_dispatch

jobs:
  too-much: # this job will only run if the PR has been merged# add check the target branch merged into is development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.ref }}
          echo  ${{ github.event_name }}
          echo  ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

          echo ${{ github.ref == 'refs/head/feature/something-0' && github.event_name == 'workflow_dispatch'}}