name: Automatic Merge release - development

on:
  workflow_dispatch:

jobs:
  merge-job-development: # this job will only run if the PR has been merged# add check the target branch merged into is development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.ref }}
          echo  ${{ github.event_name }}
          echo  ${{ github.ref == 'refs/heads/feature/STORM-4018' && github.event_name == 'push' }}